// JS folder (React)/project_exam/furniture-shop/src/core-components/header/Header.jsx
import './Header.css';

import { Link } from 'react-router-dom';
import { useContext } from 'react';
import { AuthContext } from '../../context/AuthContext';
import { logout } from '../../api-service/userService';

export default function Header() {

    const { userId, changeAuthState, updateAuthError } = useContext(AuthContext);

    const logoutUser = async () => {

        try {
            await logout();
            changeAuthState({});
        } catch (error) {
            if (error.message === '403') return updateAuthError(true);

            console.error(error.message);
        }
    }

    return (

        <header className="header-section">

            <div className='logo'>
                <Link to="/">Furniture-Shop</Link>
            </div>

            <input type="checkbox" id='sidebar-toggle' />
            <label htmlFor="sidebar-toggle" id='overlay'></label>
            <label htmlFor="sidebar-toggle" className='open-sidebar'>
                <i className='bx bx-menu bx-flip-vertical' ></i>
            </label>

            <div className='navigation-container'>

                <ul className="main-nav">
                    <label htmlFor="sidebar-toggle" className='close-sidebar'>
                        <i className='bx bx-x'></i>
                    </label>
                    <li><Link className="main" to="/">Home</Link></li>
                    <li><Link className="main" to="/shop">Shop</Link></li>
                    <li><Link className="main" to="/search">Search</Link></li>
                </ul>

                <nav className="user-nav">

                    {!!userId ?
                        <>
                            <div>
                                <Link className="user" to="/create-offer">Create Offer </Link>
                            </div>

                            <div>
                                <Link className="user" onClick={logoutUser} to="/">Logout</Link>
                            </div>

                            <div>
                                <Link className="user" to={`/profile/${userId}`}>
                                    <i className='bx bxs-user'></i>
                                </Link>
                            </div>
                        </>
                        :
                        <>
                            <div>
                                <Link className="user" to="/login">Login</Link>
                            </div>

                            <div>
                                <Link className="user" to="/register">Register</Link>
                            </div>
                        </>}

                </nav>

            </div>

        </header>

    )
}

// JS folder (Angular)/project_exam/furniture-shop/src/app/core/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { DestroyIntroductionService } from 'src/app/shared/services/destroy-introduction.service';
import { UserService } from 'src/app/shared/services/user-service.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {

  isLoggedIn: boolean = false;

  constructor(
    private userService: UserService,
    private route: Router,
  ) { }


  ngOnInit(): void {
    this.userService.loggedIn$.subscribe(curFlag => {
      this.isLoggedIn = curFlag;
    })
  }


  logoutUser(): void {

    this.userService.logout().subscribe({
      next: () => {
        this.userService.showHideUser();
      },
      error: () => {
        this.userService.showHideUser();
      }
    }
    )
  }
}

<header class="header-section">

    <div>
        <ul class="menu-container">
            <li><a class="logo" routerLink="/">Furniture-Shop</a></li>
            <li>
                <hr class="divider">
            </li>
            <li><a class="menu" routerLink="/">Home</a></li>
            <li><a class="menu" routerLink="/shop">Shop</a></li>
            <li><a class="menu" routerLink="/search">Search</a></li>
        </ul>
    </div>

    <nav class="navbar-section">

        <!--For logging users-->

        <ng-container *ngIf="isLoggedIn">
            <div>
                <a class="user" routerLink="/create-offer">Create Offer </a>
            </div>

            <div (click)="logoutUser()">
                <a routerLink="/" class="user">Logout</a>
            </div>
        </ng-container>


        <!--For guest user-->

        <ng-container *ngIf=!isLoggedIn>
            <div>
                <a class="user" routerLink="/login">Login</a>
            </div>

            <div>
                <a class="user" routerLink="/register">Register</a>
            </div>
        </ng-container>

    </nav>

</header>
