// JS folder (Angular)/project_exam/furniture-shop/src/app/core/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { DestroyIntroductionService } from 'src/app/shared/services/destroy-introduction.service';
import { UserService } from 'src/app/shared/services/user-service.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {

  isLoggedIn: boolean = false;

  constructor(
    private userService: UserService,
    private route: Router,
  ) { }


  ngOnInit(): void {
    this.userService.loggedIn$.subscribe(curFlag => {
      this.isLoggedIn = curFlag;
    })
  }


  logoutUser(): void {

    this.userService.logout().subscribe({
      next: () => {
        this.userService.showHideUser();
      },
      error: () => {
        this.userService.showHideUser();
      }
    }
    )
  }
}

<header class="header-section">

    <div>
        <ul class="menu-container">
            <li><a class="logo" routerLink="/">Furniture-Shop</a></li>
            <li>
                <hr class="divider">
            </li>
            <li><a class="menu" routerLink="/">Home</a></li>
            <li><a class="menu" routerLink="/shop">Shop</a></li>
            <li><a class="menu" routerLink="/search">Search</a></li>
        </ul>
    </div>

    <nav class="navbar-section">

        <!--For logging users-->

        <ng-container *ngIf="isLoggedIn">
            <div>
                <a class="user" routerLink="/create-offer">Create Offer </a>
            </div>

            <div (click)="logoutUser()">
                <a routerLink="/" class="user">Logout</a>
            </div>
        </ng-container>


        <!--For guest user-->

        <ng-container *ngIf=!isLoggedIn>
            <div>
                <a class="user" routerLink="/login">Login</a>
            </div>

            <div>
                <a class="user" routerLink="/register">Register</a>
            </div>
        </ng-container>

    </nav>

</header>

// JS (React)/project_exam/furniture-shop/src/core-components/header/Header.jsx
import { Link } from 'react-router-dom'

import './Header.css'

export default function Header() {
    return (

            <header className="header-section">

                <div>
                    <ul className="menu-container">
                        <li><Link className="logo" to="/">Furniture-Shop</Link></li>
                        <li><Link className="menu" to="/">Home</Link></li>
                        <li><Link className="menu" to="/shop">Shop</Link></li>
                        <li><Link className="menu" to="/search">Search</Link></li>
                    </ul>
                </div>

                <nav className="navbar-section">
                    {/* <!--For logging users--> */}
                    <div>
                        <Link className="user" to="/createOffer">Create Offer </Link>
                    </div>

                    <div>
                        <Link className="user" to="#">Logout</Link>
                    </div>

                    <div>
                        <Link className="user" to="/profile">
                            <i className='bx bxs-user'></i>
                        </Link>
                    </div>
                    {/* <!--For guest user--> */}

                    <div>
                        <Link className="user" to="/login">Login</Link>
                    </div>

                    <div>
                        <Link className="user" to="/register">Register</Link>
                    </div>
                </nav>

            </header>
            
    )
}
