// JS folder (Angular)/project_exam/furniture-shop/src/app/shared/brand-container/brand-container.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-brand-container',
  templateUrl: './brand-container.component.html',
  styleUrls: ['./brand-container.component.css']
})
export class BrandContainerComponent {

}

<div class="brand-container layout-padding2">
    <div class="box">
        <a href="">

            <!-- /only visualize at home page/ -->
            <!-- <div class="new">
                        <h5>
                            New
                        </h5>
                    </div> -->
            <div class="img-box">
                <img src="/assets/images/slider-img.png" alt="">
            </div>
            <div class="detail-box">
                <h6 class="price">
                    $100
                </h6>
                <h6>
                    Chair
                </h6>
            </div>
        </a>
    </div>
    <div class="box">
        <a href="">
            <div class="img-box">
                <img src="/assets/images/slider-img.png" alt="">
            </div>
            <div class="detail-box">
                <h6 class="price">
                    $100
                </h6>
                <h6>
                    Chair
                </h6>
            </div>
        </a>
    </div>
    <div class="box">
        <a href="">
            <div class="img-box">
                <img src="/assets/images/slider-img.png" alt="">
            </div>
            <div class="detail-box">
                <h6 class="price">
                    $100
                </h6>
                <h6>
                    Chair
                </h6>
            </div>
        </a>
    </div>
    <div class="box">
        <a href="">
            <div class="img-box">
                <img src="/assets/images/slider-img.png" alt="">
            </div>
            <div class="detail-box">
                <h6 class="price">
                    $100
                </h6>
                <h6>
                    Chair
                </h6>
            </div>
        </a>
    </div>
</div>

// JS (React)/project_exam/furniture-shop/src/shared-components/brand-container/BrandContainer.jsx
import './BrandContainer.css'

export default function BrandContainer() {

    

    return (
        <div className="brand-container layout-padding2">
        <div className="box">
            <a href="">
                <div className="new">
                    <h5>
                        New
                    </h5>
                </div>
                <div className="img-box">
                    <img src="images/slider-img.png" alt=""/>
                </div>
                <div className="detail-box">
                    <h6 className="price">
                        $100
                    </h6>
                    <h6>
                        Chair
                    </h6>
                </div>
            </a>
        </div>
        <div className="box">
            <a href="">
                <div className="img-box">
                    <img src="images/slider-img.png" alt=""/>
                </div>
                <div className="detail-box">
                    <h6 className="price">
                        $100
                    </h6>
                    <h6>
                        Chair
                    </h6>
                </div>
            </a>
        </div>
    </div>
   );
}
