// JS folder (Angular)/project_exam/furniture-shop/src/app/user/details/details.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ApiService } from 'src/app/shared/services/api.service';
import { DestroyIntroductionService } from 'src/app/shared/services/destroy-introduction.service';
import { Furniture } from 'src/app/types/furniture';

@Component({
  selector: 'app-details',
  templateUrl: './details.component.html',
  styleUrls: ['./details.component.css']
})
export class DetailsComponent implements OnInit, OnDestroy {

  currentFurniture: Furniture | undefined;
  furnitureId: string = '';
  userId: string | undefined;

  constructor(
    private introductionService: DestroyIntroductionService,
    private api: ApiService,
    private activatedRoute: ActivatedRoute,
    private router: Router,
  ) { }

  ngOnInit(): void {

    this.introductionService.hideComponent();
    this.furnitureId = this.activatedRoute.snapshot.params['id'];

    this.api.getCurrentFurniture(this.furnitureId).subscribe({
      next: (x) => {
        this.currentFurniture = x;
      }
    });

    try {
      const userId = localStorage.getItem('userId') || '';
      this.userId = JSON.parse(userId);
    } catch (error) {
      this.userId = undefined;
    }


  }

  ngOnDestroy(): void {
    this.introductionService.showComponent();
  }

  deleteFurniture(): void {
    this.api.deleteCurrentFurniture(this.furnitureId).subscribe(() => {
      this.router.navigate(['/shop']);
    });
  }

  buyFurniture(): void {
    this.api.buyCurrentFurniture(this.furnitureId).subscribe(() => {
      this.ngOnInit();
    })
  }

}

<section class="details-section layout-padding">
    <div class="container">
        <div class="heading-container">
            <h2>
                Details Furniture
            </h2>
        </div>
        <div *ngIf="currentFurniture" class="layout-padding2">

            <div class="wrapper">

                <div class="details">

                    <div class="right-box">
                        <div class="image-box">
                            <img src="{{currentFurniture.imageUrl}}" class="main-image">
                        </div>
                    </div>

                    <div class="left-box">
                        <div class="info-box">
                            <h2>Name: {{currentFurniture.name}}</h2>
                            <h3>Category: {{currentFurniture.category}}</h3>
                            <h3>Year Manufactured: {{currentFurniture.year}}</h3>
                            <h3>Materials: {{currentFurniture.materials}}</h3>
                            <h3>Condition: {{currentFurniture.condition}}</h3>
                            <h3>Price: ${{currentFurniture.price}}</h3>
                            <h3>Description: {{currentFurniture.description}}</h3>
                        </div>
                    </div>

                </div>

                <div *ngIf="!!userId" class="btn-box">

                    <ng-container *ngIf="currentFurniture.owner === userId">
                        <button routerLink="/details/edit/{{currentFurniture._id}}" class="btn">Edit</button>
                        <button (click)="deleteFurniture()" class="btn">Delete</button>
                    </ng-container>

                    <ng-container *ngIf="currentFurniture.owner !== userId">
                        <button *ngIf="!currentFurniture.buyList?.includes(userId)" (click)="buyFurniture()"
                            class="btn">Buy</button>
                        <p *ngIf="currentFurniture.buyList?.includes(userId)" class="purchase-box">
                            Thank You For Your Purchase
                        </p>
                    </ng-container>

                </div>

            </div>
        </div>
    </div>
</section>

// JS folder (React)/project_exam/furniture-shop/src/feature-components/details/Details.jsx
import './Details.css';
import Reviews from './reviews/Reviews';

import { Link, useParams } from 'react-router-dom';
import { useContext, useRef, useState } from 'react';
import { useDetailsFurniture } from '../../hooks/useFurnitureResponse';

import { AuthContext } from '../../context/AuthContext';
import { FurnitureContext } from '../../context/FurnitureContext';
import { purchaseFurniture, wishlist } from '../../api-service/furnitureService';
import { averageNumReviews } from '../../utils/averageNumReviews';
import MessageDialog from '../../shared-components/message-dialog/MessageDialog';

export default function Details() {

    const { furnitureId } = useParams();
    const furniture = useDetailsFurniture(furnitureId);
    const [isDialogOpen, setIsDialogOpen] = useState(false);
    const [quantity, setQuantity] = useState(0);
    const [changeContent, setChangeContent] = useState(true);
    const ref = useRef(null);

    const { userId, updateAuthError } = useContext(AuthContext);
    const { updateArrayState, buyList, reviews, listUserLikes, handleUserLikes } = useContext(FurnitureContext);

    function contentHandler(e) {

        if (e.target.textContent === 'Description') {
            setChangeContent(true);
        } else {
            setChangeContent(false);
        }
    }

    async function buyFurniture() {

        if (quantity === 0) return;

        try {
            await purchaseFurniture(furnitureId);
            updateArrayState(userId, 'buyList');
        } catch (error) {
            if (error.message === '403') return updateAuthError(true);

            console.error(error.message);
        }

    }

    async function updateWishlist() {

        try {
            await wishlist(furnitureId);

            handleUserLikes(userId);

        } catch (error) {
            if (error.message === '403') return updateAuthError(true);

            console.error(error.message);
        }
    }

    function scrollToReviews() {
        ref.current?.scrollIntoView({ behavior: 'smooth' });
    }

    return (

        <>
            <section className="details-section layout-padding">

                <div className="container">

                    <div className="heading-container">
                        <h2>
                            Details Furniture
                        </h2>
                    </div>

                    <div className="layout-padding2">

                        <div className="wrapper-details">

                            <div className="left-box">
                                <div className="image-box">
                                    <img src={furniture.imageUrl} className="main-image" />
                                </div>
                            </div>

                            <div className="right-box">

                                <header className="header-right">
                                    <h1>{furniture.name}</h1>
                                    <Link to={`/profile/${furniture.owner?._id}`}>
                                        <div className="profile">
                                            <img alt=""
                                                src={furniture.owner?.imageProfile ? furniture.owner?.imageProfile : '/images/profile-circle-svgrepo-com.svg'} />
                                            <div>
                                                <p>Creator:</p>
                                                <p>{furniture.owner?.username}</p>
                                            </div>
                                        </div>
                                    </Link>
                                </header>

                                <div className="box-reviews">

                                    <div className="stars">
                                        <i className={averageNumReviews() === 5 ? 'bx bxs-star active' : 'bx bxs-star'}></i>
                                        <i className={averageNumReviews() === 4 ? 'bx bxs-star active' : 'bx bxs-star'}></i>
                                        <i className={averageNumReviews() === 3 ? 'bx bxs-star active' : 'bx bxs-star'}></i>
                                        <i className={averageNumReviews() === 2 ? 'bx bxs-star active' : 'bx bxs-star'}></i>
                                        <i className={averageNumReviews() === 1 ? 'bx bxs-star active' : 'bx bxs-star'}></i>
                                    </div>

                                    <p onClick={scrollToReviews}>{reviews?.length} Reviews</p>
                                </div>

                                <div className="box-price-quantity">

                                    <div className="price">
                                        <h3>Price</h3>
                                        <p className="current-price">
                                            ${furniture.price}
                                        </p>
                                    </div>

                                    {
                                        !!userId

                                        &&

                                        userId !== furniture.owner?._id

                                        &&

                                        <div className="quantity">
                                            <h3>Quantity</h3>
                                            <div className="quantity-btn">
                                                <button name="minus" type="button" onClick={() => { if (quantity <= 0 || buyList.includes(userId)) { return } setQuantity(quantity => quantity - 1) }}><i className='bx bx-minus'></i></button>
                                                <p>{quantity}</p>
                                                <button name="plus" type="button" onClick={() => { if (buyList.includes(userId)) { return } setQuantity(quantity => quantity + 1) }}><i className='bx bx-plus'></i></button>
                                            </div>
                                        </div>
                                    }

                                </div>

                                <div className="box-description-details">

                                    <section className="content-header">
                                        <div>
                                            <p onClick={contentHandler}>Description</p>
                                            <hr className={changeContent ? 'active' : null} />
                                        </div>

                                        <div>
                                            <p onClick={contentHandler}>Details</p>
                                            <hr className={!changeContent ? 'active' : null} />
                                        </div>
                                    </section>

                                    {changeContent &&
                                        <div className="content">

                                            <div>
                                                <p>Category</p>
                                                <p>{furniture.category}</p>
                                            </div>

                                            <div>
                                                <p>Year of <abbr title="Manufacture">MFR</abbr></p>
                                                <p>{furniture.year}</p>
                                            </div>

                                            <div>
                                                <p>Condition</p>
                                                <p>{furniture.condition}</p>
                                            </div>

                                            <div>
                                                <p>Description</p>
                                                <p>{furniture.description}</p>
                                            </div>

                                        </div>
                                    }

                                    {!changeContent &&
                                        <div className="content">

                                            <div>
                                                <p>Size</p>
                                                <p>{furniture.size}</p>

                                            </div>

                                            <div>
                                                <p>Materials</p>
                                                <p>{furniture.materials}</p>
                                            </div>

                                            <div>
                                                <p>Color</p>
                                                <p>{furniture.color}</p>

                                            </div>

                                            <div>
                                                <p>Weight</p>
                                                <p>{furniture.weight}</p>
                                            </div>

                                        </div>
                                    }

                                </div>

                                {
                                    !!userId

                                    &&

                                    <div className="box-total-price">

                                        {
                                            userId !== furniture.owner?._id

                                            &&

                                            <div className="total-price">
                                                <h3>Total Price</h3>
                                                <p>${furniture.price * quantity}</p>
                                            </div>
                                        }

                                        <div className="button-box">
                                            {
                                                userId === furniture.owner?._id ?

                                                    <>
                                                        <Link className="btn-hover" to={`/edit-furniture/${furnitureId}`}>Edit</Link>
                                                        <button onClick={() => setIsDialogOpen(true)} className="btn-hover" name="delete" type="button">Delete</button>
                                                    </>

                                                    :

                                                    <>
                                                        {
                                                            buyList?.includes(userId) ?

                                                                <>
                                                                    <p className='purchase'>Thank you for your purchase!</p>
                                                                </>

                                                                :

                                                                <>
                                                                    <button onClick={buyFurniture} className={quantity > 0 ? 'btn-hover' : 'btn-hover blur'} name="add-to-cart" type="button">Buy</button>
                                                                    <button name="heart" type="button">
                                                                        <i onClick={updateWishlist} className={listUserLikes?.includes(userId) ? 'bx bxs-heart bx-tada-hover active' : 'bx bxs-heart bx-tada-hover'}></i>
                                                                    </button>
                                                                </>
                                                        }
                                                    </>
                                            }
                                        </div>

                                    </div>
                                }

                            </div>

                        </div>

                    </div>

                </div>

            </section >

            <Reviews ref={ref} />

            {isDialogOpen && <MessageDialog onClose={() => setIsDialogOpen(false)} />}

        </>

    );
}
