// JS folder (Angular)/project_exam/furniture-shop/src/app/user/details/details.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ApiService } from 'src/app/shared/services/api.service';
import { DestroyIntroductionService } from 'src/app/shared/services/destroy-introduction.service';
import { Furniture } from 'src/app/types/furniture';

@Component({
  selector: 'app-details',
  templateUrl: './details.component.html',
  styleUrls: ['./details.component.css']
})
export class DetailsComponent implements OnInit, OnDestroy {

  currentFurniture: Furniture | undefined;
  furnitureId: string = '';
  userId: string | undefined;

  constructor(
    private introductionService: DestroyIntroductionService,
    private api: ApiService,
    private activatedRoute: ActivatedRoute,
    private router: Router,
  ) { }

  ngOnInit(): void {

    this.introductionService.hideComponent();
    this.furnitureId = this.activatedRoute.snapshot.params['id'];

    this.api.getCurrentFurniture(this.furnitureId).subscribe({
      next: (x) => {
        this.currentFurniture = x;
      }
    });

    try {
      const userId = localStorage.getItem('userId') || '';
      this.userId = JSON.parse(userId);
    } catch (error) {
      this.userId = undefined;
    }


  }

  ngOnDestroy(): void {
    this.introductionService.showComponent();
  }

  deleteFurniture(): void {
    this.api.deleteCurrentFurniture(this.furnitureId).subscribe(() => {
      this.router.navigate(['/shop']);
    });
  }

  buyFurniture(): void {
    this.api.buyCurrentFurniture(this.furnitureId).subscribe(() => {
      this.ngOnInit();
    })
  }

}

<section class="details-section layout-padding">
    <div class="container">
        <div class="heading-container">
            <h2>
                Details Furniture
            </h2>
        </div>
        <div *ngIf="currentFurniture" class="layout-padding2">

            <div class="wrapper">

                <div class="details">

                    <div class="right-box">
                        <div class="image-box">
                            <img src="{{currentFurniture.imageUrl}}" class="main-image">
                        </div>
                    </div>

                    <div class="left-box">
                        <div class="info-box">
                            <h2>Name: {{currentFurniture.name}}</h2>
                            <h3>Category: {{currentFurniture.category}}</h3>
                            <h3>Year Manufactured: {{currentFurniture.year}}</h3>
                            <h3>Materials: {{currentFurniture.materials}}</h3>
                            <h3>Condition: {{currentFurniture.condition}}</h3>
                            <h3>Price: ${{currentFurniture.price}}</h3>
                            <h3>Description: {{currentFurniture.description}}</h3>
                        </div>
                    </div>

                </div>

                <div *ngIf="!!userId" class="btn-box">

                    <ng-container *ngIf="currentFurniture.owner === userId">
                        <button routerLink="/details/edit/{{currentFurniture._id}}" class="btn">Edit</button>
                        <button (click)="deleteFurniture()" class="btn">Delete</button>
                    </ng-container>

                    <ng-container *ngIf="currentFurniture.owner !== userId">
                        <button *ngIf="!currentFurniture.buyList?.includes(userId)" (click)="buyFurniture()"
                            class="btn">Buy</button>
                        <p *ngIf="currentFurniture.buyList?.includes(userId)" class="purchase-box">
                            Thank You For Your Purchase
                        </p>
                    </ng-container>

                </div>

            </div>
        </div>
    </div>
</section>

// JS (React)/project_exam/furniture-shop/src/feature-components/details/Details.jsx
import './Details.css'

import { Link, useNavigate, useParams } from 'react-router-dom';
import { useContext, useState } from 'react';
import { useDetailsFurniture } from '../../hooks/useFurnitureResponse';
import { AuthContext } from '../../context/AuthContext';
import Reviews from './reviews/Reviews';
import { purchaseFurniture, removeFurniture } from '../../service/furnitureService';

export default function Details() {

    const { furnitureId } = useParams();
    const furniture = useDetailsFurniture(furnitureId);
    const [buyFlag, setBuyFlag] = useState(false);
    const navigate = useNavigate();
    const user = useContext(AuthContext);


    async function deleteFurniture() {

        try {
            await removeFurniture(furnitureId);
            navigate('/shop');
        } catch (error) {
            console.log(error.message);
        }

    }

    async function buyFurniture() {

        try {
            await purchaseFurniture(furnitureId);
            setBuyFlag(true);
        } catch (error) {
            console.log(error.message);
        }



    }

    return (

        <>
            <section className="details-section layout-padding">

                <div className="container">

                    <div className="heading-container">
                        <h2>
                            Details Furniture
                        </h2>
                    </div>

                    <div className="layout-padding2">

                        <div className="wrapper-details">

                            <div className="left-box">
                                <div className="image-box">
                                    <img src={furniture.imageUrl} className="main-image" />
                                </div>
                            </div>

                            <div className="right-box">

                                <header className="header-right">
                                    <h1>{furniture.name}</h1>
                                    <a href="">
                                        <div className="profile">
                                            <img alt=""
                                                src="https://images.unsplash.com/photo-1502685104226-ee32379fefbe?ixlib=rb-=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=8&w=256&h=256&q=80" />
                                            <div>
                                                <p>Creator:</p>
                                                <p>Emily Selman</p>
                                            </div>
                                        </div>
                                    </a>
                                </header>

                                <div className="box-reviews">

                                    <div className="stars">
                                        <i className='bx bxs-star'></i>
                                        <i className='bx bxs-star'></i>
                                        <i className='bx bxs-star'></i>
                                        <i className='bx bxs-star'></i>
                                        <i className='bx bxs-star'></i>
                                    </div>

                                    <p>5 Reviews</p>
                                </div>

                                <div className="box-price-quantity">

                                    <div className="price">
                                        <h3>Price</h3>
                                        <p className="current-price">
                                            ${furniture.price}
                                        </p>
                                    </div>

                                    {
                                        !!user.userId

                                        &&

                                        user.userId !== furniture.owner

                                        &&

                                        buyFlag

                                        ||

                                        furniture.buyList?.includes(user.userId)

                                        ||

                                        <div className="quantity">
                                            <h3>Quantity</h3>
                                            <div className="quantity-btn">
                                                <button name="minus" type="button"><i className='bx bx-minus'></i></button>
                                                <p>2</p>
                                                <button name="plus" type="button"><i className='bx bx-plus'></i></button>
                                            </div>
                                        </div>
                                    }

                                </div>

                                <div className="box-description-details">

                                    <section className="content-header">
                                        <div>
                                            <a>Description</a>
                                            <hr id="target-one" />
                                        </div>

                                        <div>
                                            <a>Details</a>
                                            <hr id="target-two" />
                                        </div>
                                    </section>

                                    <div className="content" id='one'>

                                        <div>
                                            <p>Category</p>
                                            <p>{furniture.category}</p>
                                        </div>

                                        <div>
                                            <p>Year of <abbr title="Manufacture">MFR</abbr></p>
                                            <p>{furniture.year}</p>
                                        </div>

                                        <div>
                                            <p>Condition</p>
                                            <p>{furniture.condition}</p>
                                        </div>

                                        <div>
                                            <p>Description</p>
                                            <p>{furniture.description}</p>
                                        </div>

                                    </div>

                                    <div className="content" id='two'>

                                        <div>
                                            <p>Size</p>
                                            <p>{furniture.size}</p>

                                        </div>

                                        <div>
                                            <p>Materials</p>
                                            <p>{furniture.materials}</p>
                                        </div>

                                        <div>
                                            <p>Color</p>
                                            <p>{furniture.color}</p>

                                        </div>

                                        <div>
                                            <p>Weight</p>
                                            <p>{furniture.weight}</p>
                                        </div>

                                    </div>

                                </div>

                                {
                                    !!user.userId

                                    &&

                                    <div className="box-total-price">

                                        {
                                            user.userId !== furniture.owner

                                            &&

                                            buyFlag

                                            ||

                                            furniture.buyList?.includes(user.userId)

                                            ||

                                            <div className="total-price">
                                                <h3>Total Price</h3>
                                                <p>$600.00</p>
                                            </div>
                                        }

                                        <div className="button-box">
                                            {
                                                user.userId === furniture.owner ?

                                                    <>
                                                        <Link  className="btn-hover" to={`/edit-furniture/${furnitureId}`}>Edit</Link>
                                                        <button onClick={deleteFurniture} className="btn-hover" name="delete" type="button">Delete</button>
                                                    </>

                                                    :

                                                    <>
                                                        {
                                                            furniture.buyList?.includes(user.userId) || buyFlag ?

                                                                <>
                                                                    <p className='purchase'>Thank you for your purchase!</p>
                                                                </>

                                                                :

                                                                <>
                                                                    <button onClick={buyFurniture} className="btn-hover" name="add-to-cart" type="button">Buy</button>
                                                                    <button name="heart" type="button">
                                                                        <i className='bx bxs-heart bx-tada-hover'></i>
                                                                    </button>
                                                                </>
                                                        }
                                                    </>
                                            }
                                        </div>

                                    </div>
                                }

                            </div>

                        </div>

                    </div>

                </div>

            </section>

            <Reviews />
        </>

    );
}
