// JS (React)/project_exam/furniture-shop/src/feature-components/info-gallery/InfoGallery.jsx
import './InfoGallery.css'

export default function InfoGallery() {
    return (
        <section className="image-section layout-padding">
            <div className="container">
                <div className="image-gallery">
                    <div className="image-container">
                        <img src="images/idea_971821.png" alt="Image 1" />
                        <h2>Innovative designs</h2>
                    </div>
                    <div className="image-container">
                        <img src="images/truck_6485058.png" alt="Image 2" />
                        <h2>Fast & Free shipping</h2>
                    </div>
                    <div className="image-container">
                        <img src="images/test_3645667.png" alt="Image 3" />
                        <h2>Premium quality</h2>
                    </div>
                    <div className="image-container">
                        <img src="images/stars_5371585.png" alt="Image 4" />
                        <h2>Rated 5 stars</h2>
                    </div>
                </div>
            </div>
        </section>
    );
}

// JS folder (Angular)/project_exam/furniture-shop/src/app/features/info-gallery/info-gallery.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-info-gallery',
  templateUrl: './info-gallery.component.html',
  styleUrls: ['./info-gallery.component.css']
})
export class InfoGalleryComponent {

}

<section class="image-section layout-padding">
    <div class="container">
        <div class="image-gallery">
            <div class="image-container">
                <img src="/assets/images/idea_971821.png" alt="Image 1">
                <h2>Innovative designs</h2>
            </div>
            <div class="image-container">
                <img src="/assets/images/truck_6485058.png" alt="Image 2">
                <h2>Fast & Free shipping</h2>
            </div>
            <div class="image-container">
                <img src="/assets/images/test_3645667.png" alt="Image 3">
                <h2>Premium quality</h2>
            </div>
            <div class="image-container">
                <img src="/assets/images/stars_5371585.png" alt="Image 4">
                <h2>Rated 5 stars</h2>
            </div>
        </div>
    </div>
</section>
