// JS (React)/project_exam/furniture-shop/src/user-components/edit-furniture/Edit.jsx

import '../UserForms.css'

import { useNavigate, useParams } from 'react-router-dom';
import { useForm } from '../../hooks/useForms';
import { editFurnitureRequester } from '../../api-service/furnitureService';
import { useContext } from 'react';
import { FurnitureContext } from '../../context/FurnitureContext';



export default function Edit() {

    const navigate = useNavigate();
    const { furnitureId } = useParams();
    const furniture = useContext(FurnitureContext);

    const initialValues = {
        name: furniture.name,
        category: furniture.category,
        year: furniture.year,
        materials: furniture.materials,
        color: furniture.color,
        size: furniture.size,
        weight: furniture.weight,
        condition: furniture.condition,
        imageUrl: furniture.imageUrl,
        price: furniture.price,
        description: furniture.description,
    }

    const editFurniture = async (values) => {

        try {
            await editFurnitureRequester(furnitureId ,values);
            navigate(`/details-furniture/${furnitureId}`);
        } catch (error) {
            console.error(error.message);
        }

    }


    const { values, changeHandler, submitCurForm } = useForm(initialValues, editFurniture);

    return (
        <section className="create-offer-section layout-padding">
            <div className="container">
                <div className="heading-container">
                    <h2>
                        Edit Furniture
                    </h2>
                </div>
                <div className="layout-padding2">
                    <div className="wrapper-user">
                        <form onSubmit={submitCurForm}>

                            <div className="input-box">

                                <input
                                    type="text"
                                    placeholder="Name*"
                                    name="name"
                                    value={values.name}
                                    onChange={changeHandler}
                                />

                            </div>

                            <div className="input-box">

                                <input
                                    type="text"
                                    placeholder="Category*"
                                    name="category"
                                    value={values.category}
                                    onChange={changeHandler}
                                />

                            </div>

                            <div className="input-box">

                                <input type="number"
                                    placeholder="Year Manufactured*"
                                    name="year"
                                    value={values.year}
                                    onChange={changeHandler}
                                />
                            </div>

                            <div className="input-box">

                                <input
                                    type="text"
                                    placeholder="Materials*"
                                    name="materials"
                                    value={values.materials}
                                    onChange={changeHandler}
                                />

                            </div>

                            <div className="input-box">

                                <input
                                    type="text"
                                    placeholder="Color*"
                                    name="color"
                                    value={values.color}
                                    onChange={changeHandler}
                                />

                            </div>

                            <div className="input-box">

                                <input
                                    type="text"
                                    placeholder="Size*"
                                    name="size"
                                    value={values.size}
                                    onChange={changeHandler}
                                />

                            </div>

                            <div className="input-box">

                                <input
                                    type="text"
                                    placeholder="Weight*"
                                    name="weight"
                                    value={values.weight}
                                    onChange={changeHandler}
                                />

                            </div>

                            <div className="input-box">

                                <input
                                    type="text"
                                    placeholder="Condition*"
                                    name="condition"
                                    value={values.condition}
                                    onChange={changeHandler}
                                />

                            </div>

                            <div className="input-box">

                                <input
                                    type="text"
                                    placeholder="Image*"
                                    name="imageUrl"
                                    value={values.imageUrl}
                                    onChange={changeHandler}
                                />

                            </div>

                            <div className="input-box">

                                <input
                                    type="number"
                                    placeholder="Price*"
                                    name="price"
                                    value={values.price}
                                    onChange={changeHandler}
                                />

                            </div>

                            <div className="input-box">

                                <input
                                    type="text"
                                    placeholder="Description*"
                                    name="description"
                                    value={values.description}
                                    onChange={changeHandler}
                                />

                            </div>

                            <button type="submit" className="btn">Edit</button>

                        </form>
                    </div>
                </div>
            </div>
        </section>
    );
}

// JS folder (Angular)/project_exam/furniture-shop/src/app/user/edit/edit.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { ApiService } from 'src/app/shared/services/api.service';
import { DestroyIntroductionService } from 'src/app/shared/services/destroy-introduction.service';
import { Furniture } from 'src/app/types/furniture';

@Component({
  selector: 'app-edit',
  templateUrl: './edit.component.html',
  styleUrls: ['../user.css']

})
export class EditComponent implements OnInit, OnDestroy {

  furnitureId: string = '';

  form = this.fb.group({
    name: ['', [Validators.required, Validators.minLength(4)]],
    category: ['', [Validators.required, Validators.minLength(4)]],
    year: [0, [Validators.required, Validators.min(1900), Validators.max(2024)]],
    materials: ['', [Validators.required, Validators.minLength(10)]],
    condition: ['', [Validators.required, Validators.minLength(6)]],
    imageUrl: ['', [Validators.required]],
    price: [0, [Validators.required, Validators.min(0)]],
    description: ['', [Validators.required, Validators.minLength(10)]],
  })

  constructor(
    private introductionService: DestroyIntroductionService,
    private fb: FormBuilder,
    private router: Router,
    private activatedRoute: ActivatedRoute,
    private api: ApiService
  ) { }

  ngOnInit(): void {
    this.introductionService.hideComponent();
    this.fetchData();

  }

  ngOnDestroy(): void {
    this.introductionService.showComponent();
  }

  fetchData(): void {

    this.furnitureId = this.activatedRoute.snapshot.params['id'];

    this.api.getCurrentFurniture(this.furnitureId).subscribe({
      next: (x) => {

        this.form.setValue({
          name: x.name,
          category: x.category,
          year: x.year,
          materials: x.materials,
          condition: x.condition,
          imageUrl: x.imageUrl,
          price: x.price,
          description: x.description
        })

      }

    })

  }

  edit() {

    if (this.form.invalid) {
      return;
    }

    const payload = this.form.value;

    this.api.editFurniture(payload, this.furnitureId).subscribe(()=>{
      this.router.navigate([`/details/${this.furnitureId}`]);
    })



  }
}

<section class="create-offer-section layout-padding">
    <div class="container">

        <div class="heading-container">
            <h2>
                Edit Furniture
            </h2>
        </div>

        <div class="layout-padding2">
            <div class="wrapper">
                <form [formGroup]="form" (ngSubmit)="edit()">

                    <!-- NAME -->
                    <div class="input-box">
                        <input type="text" placeholder="Name..." name="name" formControlName="name">
                    </div>

                    <ng-container *ngIf="form.get('name')?.touched">
                        <p class="error" *ngIf="form.get('name')?.errors?.['required']">Name is required!</p>
                        <p class="error" *ngIf="form.get('name')?.errors?.['minlength']">Name should be at least 4
                            characters long.</p>
                    </ng-container>

                    <!-- CATEGORY -->
                    <div class="input-box">
                        <input type="text" placeholder="Category..." name="category" formControlName="category">
                    </div>

                    <ng-container *ngIf="form.get('category')?.touched">
                        <p class="error" *ngIf="form.get('category')?.errors?.['required']">Category is required!</p>
                        <p class="error" *ngIf="form.get('category')?.errors?.['minlength']">Category should be at least
                            4 characters long.</p>
                    </ng-container>

                    <!-- YEAR -->
                    <div class="input-box">
                        <input type="number" placeholder="Year Manufactured..." name="year" formControlName="year">
                    </div>

                    <ng-container *ngIf="form.get('year')?.touched">
                        <p class="error" *ngIf="form.get('year')?.errors?.['required']">Year is required!</p>
                        <p class="error" *ngIf="form.get('year')?.errors?.['min']">Year of the furniture should be
                            between 1900 and 2024</p>
                        <p class="error" *ngIf="form.get('year')?.errors?.['max']">Year of the furniture should be
                            between 1900 and 2024</p>
                    </ng-container>

                    <!-- MATERIALS -->
                    <div class="input-box">
                        <input type="text" placeholder="Materials..." name="materials" formControlName="materials">
                    </div>

                    <ng-container *ngIf="form.get('materials')?.touched">
                        <p class="error" *ngIf="form.get('materials')?.errors?.['required']">Materials is required!</p>
                        <p class="error" *ngIf="form.get('materials')?.errors?.['minlength']">Materials should be at
                            least 10 characters long.</p>
                    </ng-container>

                    <!-- CONDITION -->
                    <div class="input-box">
                        <input type="text" placeholder="Condition..." name="condition" formControlName="condition">
                    </div>

                    <ng-container *ngIf="form.get('condition')?.touched">
                        <p class="error" *ngIf="form.get('condition')?.errors?.['required']">Condition is required!</p>
                        <p class="error" *ngIf="form.get('condition')?.errors?.['minlength']">Condition should be at
                            least 6 characters long.</p>
                    </ng-container>

                    <!-- IMAGE -->
                    <div class="input-box">
                        <input type="text" placeholder="Image..." name="imageUrl" formControlName="imageUrl">
                    </div>

                    <ng-container *ngIf="form.get('imageUrl')?.touched">
                        <p class="error" *ngIf="form.get('imageUrl')?.errors?.['required']">Image is required!</p>
                    </ng-container>

                    <!-- PRICE -->
                    <div class="input-box">
                        <input type="number" placeholder="Price..." name="price" formControlName="price">
                    </div>

                    <ng-container *ngIf="form.get('price')?.touched">
                        <p class="error" *ngIf="form.get('price')?.errors?.['required']">Price is required!</p>
                        <p class="error" *ngIf="form.get('price')?.errors?.['min']">Price should be a positive number.
                        </p>
                    </ng-container>

                    <!-- DESCRIPTION -->
                    <div class="input-box">
                        <input type="text" placeholder="Description..." name="description"
                            formControlName="description">
                    </div>

                    <ng-container *ngIf="form.get('description')?.touched">
                        <p class="error" *ngIf="form.get('description')?.errors?.['required']">Description is required!
                        </p>
                        <p class="error" *ngIf="form.get('description')?.errors?.['minlength']">Description should be at
                            least 10 characters long.</p>
                    </ng-container>

                    <button [disabled]="form.invalid" [style]="{filter: form.invalid ? 'blur(2px)':'blur(0px)'}"
                        class="btn">Edit Furniture</button>

                </form>
            </div>
        </div>

    </div>


</section>
