// JS (React)/project_exam/furniture-shop/src/user-components/create-offer/CreateOffer.jsx
import { useNavigate } from 'react-router-dom';
import { useForm } from '../../hooks/useForms';
import { createFurnitureRequester } from '../../service/furnitureService';
import '../UserForms.css'

const initialValues = {
    name: '',
    category: '',
    year: '',
    materials: '',
    color: '',
    size: '',
    weight: '',
    condition: '',
    imageUrl: '',
    price: '',
    description: '',
}


export default function CreateOffer() {

    const navigate = useNavigate();

    const createFurniture = async (values) => {

        try {
            await createFurnitureRequester(values);
            navigate('/shop');
        } catch (error) {
            console.error(error.message);
        }

    }

    const { values, changeHandler, submitCurForm } = useForm(initialValues, createFurniture);

    return (
        <section className="create-offer-section layout-padding">
            <div className="container">
                <div className="heading-container">
                    <h2>
                        Create Offer
                    </h2>
                </div>
                <div className="layout-padding2">
                    <div className="wrapper-user">
                        <form onSubmit={submitCurForm}>

                            <div className="input-box">

                                <input
                                    type="text"
                                    placeholder="Name*"
                                    name="name"
                                    value={values.name}
                                    onChange={changeHandler}
                                />

                            </div>

                            <div className="input-box">

                                <input
                                    type="text"
                                    placeholder="Category*"
                                    name="category"
                                    value={values.category}
                                    onChange={changeHandler}
                                />

                            </div>

                            <div className="input-box">

                                <input type="number"
                                    placeholder="Year Manufactured*"
                                    name="year"
                                    value={values.year}
                                    onChange={changeHandler}
                                />
                            </div>

                            <div className="input-box">

                                <input
                                    type="text"
                                    placeholder="Materials*"
                                    name="materials"
                                    value={values.materials}
                                    onChange={changeHandler}
                                />

                            </div>

                            <div className="input-box">

                                <input
                                    type="text"
                                    placeholder="Color*"
                                    name="color"
                                    value={values.color}
                                    onChange={changeHandler}
                                />

                            </div>

                            <div className="input-box">

                                <input
                                    type="text"
                                    placeholder="Size*"
                                    name="size"
                                    value={values.size}
                                    onChange={changeHandler}
                                />

                            </div>

                            <div className="input-box">

                                <input
                                    type="text"
                                    placeholder="Weight*"
                                    name="weight"
                                    value={values.weight}
                                    onChange={changeHandler}
                                />

                            </div>

                            <div className="input-box">

                                <input
                                    type="text"
                                    placeholder="Condition*"
                                    name="condition"
                                    value={values.condition}
                                    onChange={changeHandler}
                                />

                            </div>

                            <div className="input-box">

                                <input
                                    type="text"
                                    placeholder="Image*"
                                    name="imageUrl"
                                    value={values.imageUrl}
                                    onChange={changeHandler}
                                />

                            </div>

                            <div className="input-box">

                                <input
                                    type="number"
                                    placeholder="Price*"
                                    name="price"
                                    value={values.price}
                                    onChange={changeHandler}
                                />

                            </div>

                            <div className="input-box">

                                <input
                                    type="text"
                                    placeholder="Description*"
                                    name="description"
                                    value={values.description}
                                    onChange={changeHandler}
                                />

                            </div>

                            <button type="submit" className="btn">Create Offer</button>

                        </form>
                    </div>
                </div>
            </div>
        </section>
    );
}

// JS folder (Angular)/project_exam/furniture-shop/src/app/user/create-offer/create-offer.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { DestroyIntroductionService } from 'src/app/shared/services/destroy-introduction.service';

@Component({
  selector: 'app-create-offer',
  templateUrl: './create-offer.component.html',
  styleUrls: ['../user.css']
})
export class CreateOfferComponent implements OnInit, OnDestroy {


  constructor(private introductionService: DestroyIntroductionService) { }

  ngOnInit(): void {
    this.introductionService.hideComponent();
  }

  ngOnDestroy(): void {
    this.introductionService.showComponent();
  }
}

<section class="create-offer-section layout-padding">
    <div class="container">
        <div class="heading-container">
            <h2>
                Create Offer
            </h2>
        </div>
        <div class="layout-padding2">
            <div class="wrapper">
                <form>

                    <div class="input-box">
                        <input type="text" placeholder="Name..." name="name">
                    </div>

                    <div class="input-box">
                        <input type="text" placeholder="Category..." name="category">
                    </div>

                    <div class="input-box">
                        <input type="number" placeholder="Year Manufactured..." name="category">
                    </div>

                    <div class="input-box">
                        <input type="text" placeholder="Materials..." name="materials">
                    </div>

                    <div class="input-box">
                        <input type="text" placeholder="Condition..." name="condition">
                    </div>

                    <div class="input-box">
                        <input type="text" placeholder="Image..." name="imageUrl">
                    </div>

                    <div class="input-box">
                        <input type="number" placeholder="Price..." name="price">
                    </div>

                    <div class="input-box">
                        <input type="text" placeholder="Description..." name="description">
                    </div>

                    <button class="btn">Create Offer</button>

                </form>
            </div>
        </div>
    </div>
</section>
