// JS (React)/project_exam/furniture-shop/src/user-components/login/Login.jsx
import '../UserForms.css'

import { useContext, useState } from 'react';
import { useForm } from '../../hooks/useForms';
import { login } from '../../service/userService';
import { Link, useNavigate } from 'react-router-dom'
import { AuthContext } from '../../context/AuthContext';
import { loginSchema } from '../../utils/schemaForm';

const initialValues = {
    email: '',
    password: '',
};


export default function Login() {

    const navigate = useNavigate();
    const { changeAuthState } = useContext(AuthContext)
    const [errors, setErrors] = useState({});


    const getUser = async (values) => {

        try {
            await loginSchema.validate(values, { abortEarly: false });
        } catch (error) {

            const newError = {}

            error.inner.forEach((err) => {
                newError[err.path] = err.message;
            })

            setErrors(newError);

            return;
        }

        try {
            const result = await login(values);
            changeAuthState(result);
            navigate('/');
        } catch (error) {
            console.log(error.message);
        }
    }

    const { values, changeHandler, submitCurForm } = useForm(initialValues, getUser)

    return (
        <section className="login-section layout-padding">
            <div className="container">
                <div className="heading-container">
                    <h2>
                        Login
                    </h2>
                </div>
                <div className="layout-padding2">
                    <div className="wrapper-user">
                        <form onSubmit={submitCurForm}>
                            <div className="input-box">
                                <input

                                    type="text"
                                    placeholder="Type your email*"
                                    name="email"
                                    value={values.email}
                                    onChange={changeHandler} />


                                <i className='bx bxs-envelope'></i>
                            </div>

                            {errors.hasOwnProperty('email') &&
                                <div className='error-container'>
                                    <i className='bx bxs-error-circle bx-tada' ></i>
                                    <p className='error'>{errors.email}</p>
                                </div>
                            }

                            <div className="input-box">
                                <input

                                    type="password"
                                    placeholder="Type your password*"
                                    name="password"
                                    value={values.password}
                                    onChange={changeHandler} />

                                <i className='bx bxs-lock-alt'></i>
                            </div>

                            {errors.hasOwnProperty('password') &&
                                <div className='error-container'>
                                    <i className='bx bxs-error-circle bx-tada' ></i>
                                    <p className='error'>{errors.password}</p>
                                </div>
                            }

                            <button type="submit" className="btn">Login</button>

                            <div className="link">
                                <p>Don't have and account?
                                    <Link to="/register">Register here</Link>
                                </p>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    );
}

// JS folder (Angular)/project_exam/furniture-shop/src/app/user/login/login.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { DestroyIntroductionService } from 'src/app/shared/services/destroy-introduction.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit, OnDestroy {


  constructor(private introductionService: DestroyIntroductionService){}

  ngOnInit(): void {
    this.introductionService.hideComponent();
  }

  ngOnDestroy(): void {
    this.introductionService.showComponent();
  }
}

<section class="login-section layout-padding">
    <div class="container">
        <div class="heading-container">
            <h2>
                Login
            </h2>
        </div>
        <div class="layout-padding2">
            <div class="wrapper">
                <form>
                    <div class="input-box">
                        <input type="text" placeholder="Type your email" name="email">
                        <i class='bx bxs-envelope'></i>
                    </div>

                    <div class="input-box">
                        <input type="password" placeholder="Type your password" name="password">
                        <i class='bx bxs-lock-alt'></i>
                    </div>

                    <button class="btn">Login</button>

                    <div class="link">
                        <p>Don't have and account?
                            <a routerLink="/register">Register here</a>
                        </p>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
