// JS (React)/project_exam/furniture-shop/src/feature-components/search/Search.jsx
import './Search.css'
import BrandContainer from "../../shared-components/brand-container/BrandContainer";

export default function Search() {
    return (
        <section className="search-section layout-padding">

            <div className="container">

                <div className="heading-container">
                    <h2>
                        Search
                    </h2>
                </div>

                <div className="search-form layout-padding2">
                    <div className="wrapper-search">
                        <form>
                            <div className="input-box">
                                <input type="text" name="name" className="search-input" placeholder="Enter your search name" />
                            </div>
                            <div className="input-box">
                                <input type="text" name="type" className="search-input" placeholder="Enter your search type" />
                            </div>
                            <button type="submit" className="search-button">Search</button>
                        </form>
                    </div>
                </div>

                <BrandContainer />

                <div className="no-match">
                    <h2 className=".h2">Whoops sorry no match was found!</h2>
                </div>

            </div>
        </section>
    );
}

// JS folder (Angular)/project_exam/furniture-shop/src/app/features/search/search.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { DestroyIntroductionService } from 'src/app/shared/services/destroy-introduction.service';

@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.css']
})
export class SearchComponent implements OnInit, OnDestroy {


  constructor(private introductionService: DestroyIntroductionService){}

  ngOnInit(): void {
    this.introductionService.hideComponent();
  }

  ngOnDestroy(): void {
    this.introductionService.showComponent();
  }
}

<section class="search-section layout-padding">

    <div class="container">

        <div class="heading-container">
            <h2>
                Search
            </h2>
        </div>

        <div class="search-form layout-padding2">
            <div class="wrapper">
                <form>
                    <div class="input-box">
                        <input type="text" name="name" class="search-input" placeholder="Enter your search name">
                    </div>
                    <div class="input-box">
                        <input type="text" name="type" class="search-input" placeholder="Enter your search type">
                    </div>
                    <button class="search-button">Search</button>
                </form>
            </div>
        </div>

        <app-brand-container />

        <div class="no-match">
            <h2 class=".h2">Whoops sorry no match was found!</h2>
        </div>

    </div>
</section>
