// JS folder (React)/project_exam/furniture-shop/src/shared-components/brand-container/BrandContainer.jsx
import { Link, useLocation } from 'react-router-dom';
import './BrandContainer.css'

export default function BrandContainer({ furniture }) {

    let curFurniture;
    const location = useLocation();

    if (furniture === undefined) {
        curFurniture = location.state;
    } else {
        curFurniture = furniture;
    }

    return (
        <div className="brand-container layout-padding2">

            {curFurniture?.map((furniture, index) => (

                <Link className="box" to={`/details-furniture/${furniture._id}`} key={furniture._id}>

                    <div>
                        {
                            location.pathname == '/' && index == '0' &&

                            <div className="new">
                                <h5>
                                    New
                                </h5>
                            </div>
                        }

                        <div className="img-box">
                            <img src={furniture.imageUrl[0]} alt="" />
                        </div>
                        <div className="detail-box">
                            <h6 className="price">
                                ${furniture.price}
                            </h6>
                            <h6>
                                {furniture.name}
                            </h6>
                        </div>
                    </div>

                </Link>

            ))
            }

        </div >
    );
}

// JS folder (Angular)/project_exam/furniture-shop/src/app/shared/brand-container/brand-container.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-brand-container',
  templateUrl: './brand-container.component.html',
  styleUrls: ['./brand-container.component.css']
})
export class BrandContainerComponent {

}

<div class="brand-container layout-padding2">
    <div class="box">
        <a href="">

            <!-- /only visualize at home page/ -->
            <!-- <div class="new">
                        <h5>
                            New
                        </h5>
                    </div> -->
            <div class="img-box">
                <img src="/assets/images/slider-img.png" alt="">
            </div>
            <div class="detail-box">
                <h6 class="price">
                    $100
                </h6>
                <h6>
                    Chair
                </h6>
            </div>
        </a>
    </div>
    <div class="box">
        <a href="">
            <div class="img-box">
                <img src="/assets/images/slider-img.png" alt="">
            </div>
            <div class="detail-box">
                <h6 class="price">
                    $100
                </h6>
                <h6>
                    Chair
                </h6>
            </div>
        </a>
    </div>
    <div class="box">
        <a href="">
            <div class="img-box">
                <img src="/assets/images/slider-img.png" alt="">
            </div>
            <div class="detail-box">
                <h6 class="price">
                    $100
                </h6>
                <h6>
                    Chair
                </h6>
            </div>
        </a>
    </div>
    <div class="box">
        <a href="">
            <div class="img-box">
                <img src="/assets/images/slider-img.png" alt="">
            </div>
            <div class="detail-box">
                <h6 class="price">
                    $100
                </h6>
                <h6>
                    Chair
                </h6>
            </div>
        </a>
    </div>
</div>
