// JS folder (React)/project_exam/furniture-shop/src/core-components/not-found/NotFound.jsx
import './NotFound.css'

import { Link } from 'react-router-dom'

export default function NotFound() {
    return (
        <section className="error-section layout-padding">
            <div className="container">
                <div className="heading-container">
                    <h2>
                        Error: Page Not Found!
                    </h2>
                </div>
                <div className="layout-padding2">
                    <div className="wrapper">

                        <div className="details">
                            <h2>404</h2>
                            <h4>Whoops! Page not found...</h4>
                            <p>The page you were looking for doesn't exist. You may have mistyped the address or the page
                                may have moved.</p>
                        </div>

                        <div className="a-box">
                            <Link to="/">Back To Home</Link>
                        </div>

                    </div>
                </div>
            </div>
        </section>
    );
}

// JS folder (Angular)/project_exam/furniture-shop/src/app/core/not-found/not-found.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import { DestroyIntroductionService } from 'src/app/shared/services/destroy-introduction.service';

@Component({
  selector: 'app-not-found',
  templateUrl: './not-found.component.html',
  styleUrls: ['./not-found.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class NotFoundComponent implements OnInit {

  constructor(private destroyIntroductionService: DestroyIntroductionService) {
  }

  ngOnInit(): void {
    this.destroyIntroductionService.hideComponent();
  }
  
}

<section class="not-found-section layout-padding">
    <div class="container">
        <div class="heading-container">
            <h2>
                Error: Page Not Found!
            </h2>
        </div>
        <div class="layout-padding2">

            <div class="wrapper">

                <div class="details">
                    <h2>404</h2>
                    <h4>Whoops! Page not found...</h4>
                    <p>The page you were looking for doesn't exist. You may have mistyped the address or the page
                        may have moved.</p>

                </div>

                <div class="a-box">
                    <a href="/home.html">Back To Home</a>
                </div>

            </div>
        </div>
    </div>
</section>
