// JS (React)/project_exam/furniture-shop/src/user-components/register/Register.jsx
import '../UserForms.css'
import { Link } from 'react-router-dom'

export default function Register() {
    return (
        <section className="register layout-padding">
            <div className="container">
                <div className="heading-container">
                    <h2>
                        Register
                    </h2>
                </div>
                <div className="layout-padding2">
                    <div className="wrapper-user">
                        <form>
                            <div className="input-box">
                                <input type="text" placeholder="Type your username*" name="username" />
                                <i className='bx bxs-user'></i>
                            </div>

                            <div className="input-box">
                                <input type="email" placeholder="Type your email*" name="email" />
                                <i className='bx bxs-envelope'></i>
                            </div>
                            <div className="input-box">
                                <input type="password" placeholder="Type your password*" name="password" />
                                <i className='bx bxs-lock-alt'></i>
                            </div>
                            <div className="input-box">
                                <input type="password" placeholder="Confirm your password*" name="rePassword" />
                                <i className='bx bxs-lock-alt'></i>
                            </div>

                            <button type="submit" className="btn">Register</button>

                            <div className="link">
                                <p>Already have an account?
                                    <Link to="/login">Login here</Link>
                                </p>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    );
}

// JS folder (Angular)/project_exam/furniture-shop/src/app/user/register/register.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { DestroyIntroductionService } from 'src/app/shared/services/destroy-introduction.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['../user.css']
})
export class RegisterComponent implements OnInit, OnDestroy {


  constructor(private introductionService: DestroyIntroductionService) { }

  ngOnInit(): void {
    this.introductionService.hideComponent();
  }

  ngOnDestroy(): void {
    this.introductionService.hideComponent();
  }
}

<section class="register layout-padding">
    <div class="container">
        <div class="heading-container">
            <h2>
                Register
            </h2>
        </div>
        <div class="layout-padding2">
            <div class="wrapper">
                <form>
                    <div class="input-box">
                        <input type="text" placeholder="Type your username" name="username">
                        <i class='bx bxs-user'></i>
                    </div>

                    <div class="input-box">
                        <input type="text" placeholder="Type your email" name="email">
                        <i class='bx bxs-envelope'></i>
                    </div>
                    <div class="input-box">
                        <input type="password" placeholder="Type your password" name="password">
                        <i class='bx bxs-lock-alt'></i>
                    </div>
                    <div class="input-box">
                        <input type="password" placeholder="Confirm your password" name="rePassword">
                        <i class='bx bxs-lock-alt'></i>
                    </div>

                    <button class="btn">Register</button>

                    <div class="link">
                        <p>Already have an account?
                            <a routerLink="/login">Login here</a>
                        </p>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
