// JS (React)/project_exam/furniture-shop/src/feature-components/shop/Shop.jsx
import BrandContainer from "../../shared-components/brand-container/BrandContainer";

export default function Shop() {
    return (
        <section className="brand-section layout-padding">
            <div className="container">

                <div className="heading-container">
                    <h2>
                        Products
                    </h2>
                </div>

                <BrandContainer />

            </div>
        </section>
    );
}

// JS folder (Angular)/project_exam/furniture-shop/src/app/features/shop/shop.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { DestroyIntroductionService } from 'src/app/shared/services/destroy-introduction.service';

@Component({
  selector: 'app-shop',
  templateUrl: './shop.component.html',
  styleUrls: ['./shop.component.css']
})
export class ShopComponent implements OnInit, OnDestroy {


  constructor(private introductionService: DestroyIntroductionService){}

  ngOnInit(): void {
    this.introductionService.hideComponent();
  }

  ngOnDestroy(): void {
    this.introductionService.showComponent();
  }

}

<section class="brand-section layout-padding">
    <div class="container">
        <div class="heading-container">
            <h2>
                Products
            </h2>
        </div>
        <app-brand-container />
    </div>
</section>
